site_name: Support Documents
theme:
  name: material

docs_dir: files
watch:
  - files

# page tree
nav: 
  - User Guide: index.md
  - Data Guide: data_standardization.md

plugins:
  - git-revision-date-localized:
      type: date
